### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassos#13]
- [x] Active rauc timer
- [x] Disable system1 on init in dts for EFI
- [x] Implement PKI
- [x]  Fix expander after rename
- [x] Use AppArmor from URL (http://s3.amazonaws.com/hassio-version/apparmor.txt)
- [x] Use official defconfig for u-boot
