### ISSUE TITLE
Roadmap Release REL-3

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassos#214]
I will create a new major release in 2018. Follow work need to be done for it:

Need:

- [x] Add support for config in boot partition (also into REL-1)
- [x] Update Buildroot to 2018.11
- [x] Change uboot script environment handling like odroid C2 (CC @rbray89)
- [x] Update docker to 18.09
- [ ] Split global kernel file into a second one with HassOS specific options
- [ ] Add odroid xu3/4
- [ ] Add Intel-nuc (need only a usb installer, all other will work like ova)

Maybe:

- [ ] Script that allow to export data partition to a external harddisk
