### ISSUE TITLE
Roadmap for release

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassos#3]
*In progress*

# Tasks Supervisor
- [x] dbus support
- [ ] Host config support over dbus

# Tasks CLI
- [ ] Make a real CLI docker image

# Tasks OS
- [x] Cleanup filesystem
- [x] Fix barebox state access
- [x] Make a nice barebox menu
- [x] Update OS/Version data
- [ ] Automatic Rauc OTA updates

# Supported Hardware on beta release
- [x] OVF/OVA
- [x] Raspberry Pi
- [x] Raspberry Pi 2
- [x] Raspberry Pi 3/+

# Supported Hardware on stable release (Need hardware donation)
- [ ] Orange Pi
- [ ] Pine
- [ ] Rock64

**Comment by CookieMonster87** [comment]
Is support for Asus Tinker Board S also planned or considered? :)

**Comment by bcran** [comment]
I just installed the 0.6 release on my new Raspberry Pi 3 B+ and it appears to be working - so it seems the "Supported Hardware on beta release" list needs updated :)

**Comment by mories76** [comment]
I have a rock64 with emmc, so I can do some testing if needed.
